sudo: required

language: java

cache:
  directories:
    - $HOME/.m2
    - $HOME/.embedpostgresql

before_install:
  - java -version

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8
#    - dist: trusty
#      sudo: required
#      group: edge
#      jdk: oraclejdk9
#      addons:
#        apt:
#          packages:
#          - oracle-java9-installer
#      script:
#      - jdk_switcher use oraclejdk9
#      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
