sudo: required

language: java

cache:
  directories:
    - $HOME/.m2
    - $HOME/.embedpostgresql

before_install:
  - java -version

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8
    - dist: trusty
      group: edge
      jdk: oraclejdk9
